# Generated by Django 3.2.21 on 2023-12-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20231209_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='item_name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='notes',
            field=models.TextField(blank=True, max_length=300, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
    ]
