# Generated by Django 3.2.21 on 2023-12-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20231209_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='cuisine',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='cuisine'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='item_name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='name'),
        ),
    ]
