# Generated by Django 3.2.21 on 2023-12-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20231209_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='name'),
        ),
    ]
