# Generated by Django 3.2.21 on 2023-12-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20231209_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
