# Generated by Django 3.2.21 on 2023-12-10 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20231210_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='star_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
