# Generated by Django 3.2.21 on 2023-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_menuitem_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='notes',
            field=models.TextField(blank=True, max_length=300, verbose_name='notes'),
        ),
    ]
