# Generated by Django 3.2.21 on 2023-12-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_menuitem_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_items',
            field=models.ManyToManyField(to='auctions.MenuItem'),
        ),
    ]
