# Generated by Django 3.2.21 on 2023-12-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_restaurant_menu_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ManyToManyField(to='auctions.Restaurant'),
        ),
    ]
