# Generated by Django 3.2.22 on 2023-12-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20231210_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_items',
            field=models.ManyToManyField(to='auctions.MenuItem'),
        ),
    ]
