# Generated by Django 3.2.22 on 2023-12-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20231210_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='creator',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_items',
            field=models.ManyToManyField(to='auctions.MenuItem'),
        ),
    ]
