# Generated by Django 3.2.22 on 2023-12-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20231210_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_name',
            field=models.CharField(max_length=150, verbose_name='item_name'),
        ),
    ]
